[settings]
os=Android
os.api_level=28
arch=armv7
compiler=clang
compiler.version=17
compiler.libcxx=c++_shared
build_type=Release
[tool_requires]
cmake/3.23.5
android-ndk/r26b@de.privatehive/stable
android-sdk/latest@de.privatehive/stable
openjdk/19.0.2@de.privatehive/stable
